language: python

services:
  - docker

before_install:
  - pip3 install -r requirements.txt
  - LATEST_GHOST_VERSION=$(python3 ghost_version.py)
  - docker build -t tomjsalmon/ghost-docker --build-arg GHOST_VERSION: $LATEST_GHOST_VERSION .
  - docker run -d -p 127.0.0.1:80:2368 -e GHOST_URL=example.tomsalmon.net tomjsalmon/ghost-docker
